"""Scan command -- analyze MCP servers for security and description quality."""

import click
from rich.console import Console

console = Console()


@click.command()
@click.argument("target")
@click.option("--output", "-o", default=None, help="Output report path (JSON/SARIF)")
@click.option(
    "--format", "fmt",
    type=click.Choice(["table", "json", "sarif", "spiderrating"]),
    default="table",
)
@click.option("--tools-json", default=None, help="Pre-extracted tools JSON (MCP tools/list format)")
@click.option("--policy", "policy_output", default=None, help="Generate security policy YAML to this path")
def scan(target: str, output: str | None, fmt: str, tools_json: str | None, policy_output: str | None):
    """Scan an MCP server for security issues and description quality.

    TARGET can be a GitHub repo URL or a local directory path.

    Use --format spiderrating to output in SpiderRating-compatible JSON
    (description 35% + security 35% + metadata 30%, F/D/C/B/A grades).

    Use --policy to auto-generate a security policy YAML from scan results.
    """
    if fmt == "sarif":
        from pathlib import Path

        from spidershield.agent.sarif import sarif_to_json, scan_report_to_sarif
        from spidershield.scanner.runner import run_scan_report

        report = run_scan_report(target, tools_json=tools_json)
        sarif = scan_report_to_sarif(report)
        sarif_json = sarif_to_json(sarif)
        if output:
            Path(output).write_text(sarif_json, encoding="utf-8")
            Console(stderr=True).print(f"[green]SARIF report written to {output}[/green]")
        else:
            console.print(sarif_json)
    elif fmt == "spiderrating":
        import json
        from pathlib import Path as SpiderPath

        from spidershield.scanner.runner import run_scan_report

        report = run_scan_report(target, tools_json=tools_json)
        report_dict = json.loads(report.model_dump_json())

        from spidershield.spiderrating import convert, parse_owner_repo

        try:
            owner, repo = parse_owner_repo(target)
        except ValueError:
            owner, repo = "local", SpiderPath(target).name

        result = convert(report_dict, owner, repo)
        json_str = json.dumps(result, indent=2)

        if output:
            SpiderPath(output).write_text(json_str, encoding="utf-8")
            Console(stderr=True).print(f"[green]SpiderRating JSON written to {output}[/green]")
        else:
            # Use plain print (not Rich console.print) to avoid Rich markup processing
            # corrupting JSON bracket sequences like ["tool", "[arg]"]
            print(json_str)
    else:
        from spidershield.scanner.runner import run_scan

        run_scan(target, output_path=output, output_format=fmt, tools_json=tools_json)

    # ── Policy YAML generation (optional) ──────────────────────────
    if policy_output:
        _generate_policy(target, policy_output, tools_json)


def _generate_policy(target: str, policy_output: str, tools_json: str | None) -> None:
    """Generate a security policy YAML from scan results."""
    import json
    import re
    from pathlib import Path

    from spidershield.scanner.runner import run_scan_report
    from spidershield.spiderrating import convert, parse_owner_repo

    report = run_scan_report(target, tools_json=tools_json)
    report_dict = json.loads(report.model_dump_json())

    try:
        owner, repo = parse_owner_repo(target)
    except ValueError:
        owner, repo = "local", Path(target).name

    result = convert(report_dict, owner, repo)

    # Extract tools and issues
    tools = result.get("tools", [])
    score_data = result.get("score", {})
    security = score_data.get("security", {}) if isinstance(score_data, dict) else {}
    issues = security.get("issues", []) if isinstance(security, dict) else []
    overall = score_data.get("overall") if isinstance(score_data, dict) else None
    grade = score_data.get("grade") if isinstance(score_data, dict) else None

    # Classify tools
    write_re = re.compile(
        r"(?:^|[-_])(create|update|write|set|put|insert|add|post|send|push|upload|save|modify|edit|patch)(?:[-_]|$)",
        re.IGNORECASE,
    )
    destructive_re = re.compile(
        r"(?:^|[-_])(delete|remove|drop|destroy|purge|clear|reset|revoke|terminate|kill|truncate)(?:[-_]|$)",
        re.IGNORECASE,
    )
    read_re = re.compile(
        r"(?:^|[-_])(get|list|read|search|find|fetch|query|lookup|check|show|describe|count|browse|view|export)(?:[-_]|$)",
        re.IGNORECASE,
    )

    has_critical = any(i.get("severity") == "critical" for i in issues)
    slug = f"{owner}/{repo}"

    lines = [
        f"# Auto-generated security policy for {slug}",
        f"# Score: {overall}/10, Grade: {grade}" if overall else "# Score: unknown",
        f"# Tools: {len(tools)}, Issues: {len(issues)}",
        f"# Generated by: spidershield scan --policy",
        f"name: {owner}-{repo}-auto",
        f"server: {slug}",
    ]
    if overall is not None:
        lines.append(f"score: {overall}")
    if grade:
        lines.append(f"grade: {grade}")
    lines.append("")
    lines.append("rules:")

    for tool in tools:
        name = tool.get("name", "")
        tool_score = tool.get("score")

        if destructive_re.search(name):
            cat, decision, reason = "destructive", "deny", "Destructive operation — blocked by default"
        elif write_re.search(name) and has_critical:
            cat, decision, reason = "write", "escalate", "Write operation on server with security findings"
        elif tool_score is not None and tool_score < 3.0:
            cat, decision, reason = "low-quality", "escalate", f"Low description quality ({tool_score:.1f}/10)"
        elif write_re.search(name):
            cat, decision, reason = "write", "allow", ""
        elif read_re.search(name):
            cat, decision, reason = "read", "allow", ""
        else:
            cat, decision, reason = "unknown", "allow", ""

        lines.append(f"  - tool: \"{name}\"")
        lines.append(f"    decision: {decision}")
        lines.append(f"    category: {cat}")
        if reason:
            lines.append(f"    reason: \"{reason}\"")

    # Warnings
    if issues:
        lines.append("")
        lines.append("# Security warnings:")
        critical_count = sum(1 for i in issues if i.get("severity") == "critical")
        high_count = sum(1 for i in issues if i.get("severity") == "high")
        if critical_count:
            lines.append(f"#   - {critical_count} critical issue(s)")
        if high_count:
            lines.append(f"#   - {high_count} high severity issue(s)")

    yaml_content = "\n".join(lines) + "\n"

    Path(policy_output).write_text(yaml_content, encoding="utf-8")
    console.print(f"[green]Policy YAML written to {policy_output}[/green]")
    console.print(f"  {len(tools)} tools classified, {len(issues)} security issues referenced")
